# Generated by Django 5.2.18 on 2026-10-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True, verbose_name="identifiant de l'événement Stripe")),
                ('event_type', models.CharField(max_length=100, verbose_name="type d'événement")),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='reçu le')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_events', to='booking.booking', verbose_name='réservation')),
            ],
            options={
                'verbose_name': 'événement Stripe',
                'verbose_name_plural': 'événements Stripe',
                'db_table': 'stripe_events',
                'ordering': ['-received_at'],
            },
        ),
    ]
