# Generated by Django 5.2.18 on 2026-10-10 08:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme', '0002_movie_duration_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="seuil d'alerte (%)")),
            ],
            options={
                'verbose_name': 'réglage des alertes',
                'verbose_name_plural': 'réglage des alertes',
                'db_table': 'alert_settings',
            },
        ),
        migrations.CreateModel(
            name='OccupancyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_rate', models.PositiveSmallIntegerField(verbose_name="taux lors de l'alerte (%)")),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='envoyée le')),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_alert', to='programme.screening', verbose_name='séance')),
            ],
            options={
                'verbose_name': 'alerte de remplissage',
                'verbose_name_plural': 'alertes de remplissage',
                'db_table': 'occupancy_alerts',
                'ordering': ['-sent_at'],
            },
        ),
    ]
