# Generated by Django 5.2.18 on 2026-10-10 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField(default=datetime.date(2026, 10, 1), verbose_name='date de lancement')),
                ('festival_start', models.DateField(blank=True, null=True, verbose_name='début du festival')),
                ('festival_end', models.DateField(blank=True, null=True, verbose_name='fin du festival')),
            ],
            options={
                'verbose_name': 'réglage des indicateurs',
                'verbose_name_plural': 'réglage des indicateurs',
                'db_table': 'kpi_settings',
            },
        ),
    ]
