# Generated by Django 5.2.18 on 2026-10-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='échecs de connexion consécutifs'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="verrouillé jusqu'au"),
        ),
    ]
