# Generated by Django 5.2.18 on 2026-10-06 16:12

import booking.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default=booking.models.generate_reference, editable=False, max_length=8, unique=True, verbose_name='référence')),
                ('channel', models.CharField(choices=[('WEB', 'En ligne'), ('BOX_OFFICE', 'Guichet')], max_length=10, verbose_name='canal')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('CONFIRMED', 'Confirmée'), ('EXPIRED', 'Expirée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=10, verbose_name='statut')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='adresse e-mail')),
                ('customer_postcode', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('customer_country', models.CharField(blank=True, max_length=2, verbose_name='pays (code ISO)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='montant total (€)')),
                ('payment_method', models.CharField(blank=True, choices=[('ONLINE_CARD', 'Carte en ligne (Stripe)'), ('CASH', 'Espèces'), ('CARD_TERMINAL', 'Carte (terminal du guichet)')], max_length=15, verbose_name='mode de paiement')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='session de paiement Stripe')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expiration du blocage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmée le')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='programme.screening', verbose_name='séance')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='vendu par')),
            ],
            options={
                'verbose_name': 'réservation',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='prix payé (€)')),
                ('status', models.CharField(choices=[('HELD', 'Bloquée'), ('SOLD', 'Vendue')], default='HELD', max_length=4, verbose_name='statut')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='scanné le')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.booking', verbose_name='réservation')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='programme.price', verbose_name='tarif')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='scanné par')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='programme.screening', verbose_name='séance')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='programme.seat', verbose_name='place')),
            ],
            options={
                'verbose_name': 'billet',
                'db_table': 'tickets',
                'ordering': ['seat__row', 'seat__number'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='booking_status_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('channel', 'BOX_OFFICE'), models.Q(('customer_email', ''), _negated=True), _connector='OR'), name='web_booking_requires_email'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('screening', 'seat'), name='unique_seat_per_screening'),
        ),
    ]
