# Generated by Django 5.2.18 on 2026-10-07 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('programme', '0002_movie_duration_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='web_booking_requires_email',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('channel', 'BOX_OFFICE'), models.Q(('customer_email', ''), _negated=True), models.Q(('status', 'CONFIRMED'), _negated=True), _connector='OR'), name='web_booking_requires_email'),
        ),
    ]
