# Generated by Django 5.2.18 on 2026-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_web_email_on_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2, verbose_name='langue'),
        ),
    ]
