# Generated by Django 5.2.18 on 2026-10-06 16:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('synopsis', models.TextField(verbose_name='synopsis')),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='durée (minutes)')),
                ('poster', models.ImageField(blank=True, upload_to='posters/', verbose_name='affiche')),
                ('rating', models.CharField(choices=[('TP', 'Tous publics'), ('-12', 'Interdit aux moins de 12 ans'), ('-16', 'Interdit aux moins de 16 ans'), ('-18', 'Interdit aux moins de 18 ans')], default='TP', max_length=3, verbose_name='classification')),
                ('version', models.CharField(choices=[('VF', 'Version française'), ('VOST', 'Version originale sous-titrée')], max_length=4, verbose_name='version')),
                ('is_young_audience', models.BooleanField(default=False, verbose_name='jeune public')),
            ],
            options={
                'verbose_name': 'film',
                'db_table': 'movies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix (€)')),
                ('requires_proof', models.BooleanField(default=False, verbose_name="justificatif demandé à l'entrée")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'tarif',
                'db_table': 'prices',
                'ordering': ['-amount'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('category', models.CharField(choices=[('PREMIUM', 'Premium / IMAX'), ('STANDARD', 'Standard'), ('VIP', 'VIP'), ('EVENT', 'Événementielle')], max_length=10, verbose_name='catégorie')),
                ('supplement', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='supplément (€)')),
            ],
            options={
                'verbose_name': 'salle',
                'db_table': 'rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='début')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmée'), ('CANCELLED', 'Annulée')], default='SCHEDULED', max_length=10, verbose_name='statut')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='programme.movie', verbose_name='film')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='programme.room', verbose_name='salle')),
            ],
            options={
                'verbose_name': 'séance',
                'db_table': 'screenings',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2, verbose_name='rangée')),
                ('number', models.PositiveSmallIntegerField(verbose_name='numéro')),
                ('is_accessible', models.BooleanField(default=False, verbose_name='place PMR')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='programme.room', verbose_name='salle')),
            ],
            options={
                'verbose_name': 'place',
                'db_table': 'seats',
                'ordering': ['room', 'row', 'number'],
                'constraints': [models.UniqueConstraint(fields=('room', 'row', 'number'), name='unique_seat_position')],
            },
        ),
    ]
