# Generated by Django 5.2.18 on 2026-10-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1)), name='movie_duration_positive'),
        ),
    ]
