BEGIN;
--
-- Create model User
--
CREATE TABLE "users" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "role" varchar(20) NOT NULL);
CREATE TABLE "users_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "users_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE INDEX "users_email_0ea73cca_like" ON "users" ("email" varchar_pattern_ops);
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_user_id_group_id_fc7788e8_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_user_id_f500bee5_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_group_id_2f3517aa_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_groups_user_id_f500bee5" ON "users_groups" ("user_id");
CREATE INDEX "users_groups_group_id_2f3517aa" ON "users_groups" ("group_id");
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissions_user_id_permission_id_3b86cbdf_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissions_user_id_92473840_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissio_permission_id_6d08dcd2_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_user_permissions_user_id_92473840" ON "users_user_permissions" ("user_id");
CREATE INDEX "users_user_permissions_permission_id_6d08dcd2" ON "users_user_permissions" ("permission_id");
COMMIT;
BEGIN;
--
-- Create model Movie
--
CREATE TABLE "movies" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "synopsis" text NOT NULL, "duration_minutes" smallint NOT NULL CHECK ("duration_minutes" >= 0), "poster" varchar(100) NOT NULL, "rating" varchar(3) NOT NULL, "version" varchar(4) NOT NULL, "is_young_audience" boolean NOT NULL);
--
-- Create model Price
--
CREATE TABLE "prices" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "label" varchar(50) NOT NULL UNIQUE, "amount" numeric(6, 2) NOT NULL, "requires_proof" boolean NOT NULL, "is_active" boolean NOT NULL);
--
-- Create model Room
--
CREATE TABLE "rooms" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL UNIQUE, "category" varchar(10) NOT NULL, "supplement" numeric(5, 2) NOT NULL);
--
-- Create model Screening
--
CREATE TABLE "screenings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "starts_at" timestamp with time zone NOT NULL, "status" varchar(10) NOT NULL, "movie_id" bigint NOT NULL, "room_id" bigint NOT NULL);
--
-- Create model Seat
--
CREATE TABLE "seats" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "row" varchar(2) NOT NULL, "number" smallint NOT NULL CHECK ("number" >= 0), "is_accessible" boolean NOT NULL, "is_active" boolean NOT NULL, "room_id" bigint NOT NULL, CONSTRAINT "unique_seat_position" UNIQUE ("room_id", "row", "number"));
CREATE INDEX "prices_label_12685f8e_like" ON "prices" ("label" varchar_pattern_ops);
CREATE INDEX "rooms_name_c1185204_like" ON "rooms" ("name" varchar_pattern_ops);
ALTER TABLE "screenings" ADD CONSTRAINT "screenings_movie_id_f64bb7d9_fk_movies_id" FOREIGN KEY ("movie_id") REFERENCES "movies" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "screenings" ADD CONSTRAINT "screenings_room_id_bf66250f_fk_rooms_id" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "screenings_starts_at_8b618567" ON "screenings" ("starts_at");
CREATE INDEX "screenings_movie_id_f64bb7d9" ON "screenings" ("movie_id");
CREATE INDEX "screenings_room_id_bf66250f" ON "screenings" ("room_id");
ALTER TABLE "seats" ADD CONSTRAINT "seats_room_id_1d1647c1_fk_rooms_id" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "seats_room_id_1d1647c1" ON "seats" ("room_id");
COMMIT;
BEGIN;
--
-- Create model Booking
--
CREATE TABLE "bookings" ("id" uuid NOT NULL PRIMARY KEY, "reference" varchar(8) NOT NULL UNIQUE, "channel" varchar(10) NOT NULL, "status" varchar(10) NOT NULL, "customer_name" varchar(100) NOT NULL, "customer_email" varchar(254) NOT NULL, "customer_postcode" varchar(10) NOT NULL, "customer_country" varchar(2) NOT NULL, "total_amount" numeric(7, 2) NOT NULL, "payment_method" varchar(15) NOT NULL, "stripe_session_id" varchar(255) NULL UNIQUE, "expires_at" timestamp with time zone NULL, "created_at" timestamp with time zone NOT NULL, "confirmed_at" timestamp with time zone NULL, "screening_id" bigint NOT NULL, "sold_by_id" bigint NULL);
--
-- Create model Ticket
--
CREATE TABLE "tickets" ("id" uuid NOT NULL PRIMARY KEY, "unit_price" numeric(6, 2) NOT NULL, "status" varchar(4) NOT NULL, "scanned_at" timestamp with time zone NULL, "booking_id" uuid NOT NULL, "price_id" bigint NOT NULL, "scanned_by_id" bigint NULL, "screening_id" bigint NOT NULL, "seat_id" bigint NOT NULL);
--
-- Create index booking_status_expiry_idx on field(s) status, expires_at of model booking
--
CREATE INDEX "booking_status_expiry_idx" ON "bookings" ("status", "expires_at");
--
-- Create constraint web_booking_requires_email on model booking
--
ALTER TABLE "bookings" ADD CONSTRAINT "web_booking_requires_email" CHECK (("channel" = 'BOX_OFFICE' OR NOT ("customer_email" = '')));
--
-- Create constraint unique_seat_per_screening on model ticket
--
ALTER TABLE "tickets" ADD CONSTRAINT "unique_seat_per_screening" UNIQUE ("screening_id", "seat_id");
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_screening_id_ba4b2452_fk_screenings_id" FOREIGN KEY ("screening_id") REFERENCES "screenings" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_sold_by_id_ab960f70_fk_users_id" FOREIGN KEY ("sold_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "bookings_reference_2af8917e_like" ON "bookings" ("reference" varchar_pattern_ops);
CREATE INDEX "bookings_stripe_session_id_6cd86472_like" ON "bookings" ("stripe_session_id" varchar_pattern_ops);
CREATE INDEX "bookings_screening_id_ba4b2452" ON "bookings" ("screening_id");
CREATE INDEX "bookings_sold_by_id_ab960f70" ON "bookings" ("sold_by_id");
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_booking_id_d9ce02d0_fk_bookings_id" FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_price_id_8ae7ffb4_fk_prices_id" FOREIGN KEY ("price_id") REFERENCES "prices" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_scanned_by_id_4a3006b4_fk_users_id" FOREIGN KEY ("scanned_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_screening_id_f6d64d02_fk_screenings_id" FOREIGN KEY ("screening_id") REFERENCES "screenings" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_seat_id_e8dc5a36_fk_seats_id" FOREIGN KEY ("seat_id") REFERENCES "seats" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "tickets_booking_id_d9ce02d0" ON "tickets" ("booking_id");
CREATE INDEX "tickets_price_id_8ae7ffb4" ON "tickets" ("price_id");
CREATE INDEX "tickets_scanned_by_id_4a3006b4" ON "tickets" ("scanned_by_id");
CREATE INDEX "tickets_screening_id_f6d64d02" ON "tickets" ("screening_id");
CREATE INDEX "tickets_seat_id_e8dc5a36" ON "tickets" ("seat_id");
COMMIT;
BEGIN;
--
-- Create model StripeEvent
--
CREATE TABLE "stripe_events" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "event_id" varchar(255) NOT NULL UNIQUE, "event_type" varchar(100) NOT NULL, "received_at" timestamp with time zone NOT NULL, "booking_id" uuid NULL);
ALTER TABLE "stripe_events" ADD CONSTRAINT "stripe_events_booking_id_4ae9f04d_fk_bookings_id" FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "stripe_events_event_id_ac37df96_like" ON "stripe_events" ("event_id" varchar_pattern_ops);
CREATE INDEX "stripe_events_booking_id_4ae9f04d" ON "stripe_events" ("booking_id");
COMMIT;
